name: Linting

on: [push]

jobs:
  lint:
    name: Static code analysis / Linting
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: npm install
      run: npm install
    - name: Linting
      run: npx run-p check:*
